#!/usr/bin/env bash
# This script loops from 1 to 10


count="1"
while [ $count -lt 10 ]
do
	count=$((count+1))
	echo "Best School"

	if [ $count -eq 4 ];then
		echo "bad luck"
	elif [ $count -eq 7 ];then
		echo "good luck"
	fi
done
