#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
# 	displays 4 and then bad luck from China for 4th iteration
#	displays 9 and then bad luck from Japan for 9th iteration
#	displays 17 and then bad luck from Italy for 17th iteration

count=0

while [ $count -lt 20 ]
do
	
	echo "$((count+1))"
	
	case $count in 
	3)
	echo "bad luck from China"
	;;
	8)
	echo "bad luck from Japan"
	;;
	16)	
	echo "bad luck from Italy"
	;;
	esac

	count=$((count + 1))
done

